services:
  python_misha:
    container_name: python_misha
    ports:
      - "5000:5000"
    build:
      dockerfile: Dockerfile
    networks:
      - python-network

networks:
  python-network:
    name: backend_network
    external: true
